GET http://localhost:8000/admin/ HTTP/1.1

###
POST http://localhost:8000/admin/add HTTP/1.1
Content-Type: application/json

{
    "useremail": "tm-l@live.se",
    "password": "hejadmin1",
}


###

POST http://localhost:8000/users/add HTTP/1.1
Content-Type: application/json

{
    "firstname": "Esaa",
    "lastname": "Lindholm",
    "useremail": "test45665@mail.com",
    "password": "he234324j123",
    "phone": "07623435",
    "address": "Vårgatan 1",
    "city": "Höganäs",
    "zip": "26334"
}

###

GET http://localhost:8000/users/ HTTP/1.1

###
POST http://localhost:8000/pets/add HTTP/1.1
Content-Type: application/json

{
    "name": "Boston",
    "petType": "Hund",
    "breed": "Cane Corso",
    "color": "fawn",
    "image": "",
    "chipNr": "565012065",
    "details": "Höganäs",
    "ownerId": "26516181102"
}

###
GET http://localhost:8000/pets/owner/63c540a51475749c5ac2d089 HTTP/1.1

###
DELETE http://localhost:8000/pets/63c544931475749c5ac2d08b HTTP/1.1

###
POST http://localhost:8000/admin/login HTTP/1.1
Content-Type: application/json

{
    "useremail": "tm-l@live.se",
    "password": "hejehj456",
}

###
POST http://localhost:8000/users/login HTTP/1.1
Content-Type: application/json

{
    "useremail": "tm-l@live.se",
    "password": "hejehj456"
}